---
properties:
- name: PREFIX
  value: "{{toolchain.name}}"
  type: text
- name: VPC_IMAGE_NAME
  value: "${PREFIX}"
  type: text
- name: COS_SERVICE_NAME
  value: "${PREFIX}-cos"
  type: text
- name: COS_SERVICE_PLAN
  value: "standard"
  type: text
- name: COS_REGION
  value: "${REGION}"
  type: text
- name: COS_BUCKET_NAME
  value: "${PREFIX}-images"
  type: text
- name: DATACENTER
  value: "${DATACENTER}"
  type: text
- name: REGION
  value: "${REGION}"
  type: text
- name: RESOURCE_GROUP_NAME
  value: "${RESOURCE_GROUP_NAME}"
  type: text
- name: IBMCLOUD_API_KEY
  value: "${API_KEY}"
  type: secure
- name: SOFTLAYER_USERNAME
  value: "${SOFTLAYER_USERNAME}"
  type: text
- name: SOFTLAYER_API_KEY
  value: "${SOFTLAYER_API_KEY}"
  type: secure

stages:
- name: '012 Initialize and Create Initial VSI'
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: git
    events: '{"push":true,"pull_request":false,"pull_request_closed":false}'
  jobs:
  - name: 012build
    type: builder
    build_type: customimage
    script: |+
      #!/bin/bash
      ./vpc-migrate-from-classic/pipeline_build.sh \
        000-prereqs.sh \
        010-prepare-cos.sh \
        020-create-classic-vm.sh
    docker_image: l2fprod/bxshell:latest

- name: '3 Capture Initial VSI VHD to COS bucket'
  inputs:
  - type: job
    stage: '012 Initialize and Create Initial VSI'
    job: 012build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 3build
    type: builder
    build_type: customimage
    script: |+
      #!/bin/bash
      ./vpc-migrate-from-classic/pipeline_build.sh \
        030-capture-classic-to-cos.sh
    docker_image: l2fprod/bxshell:latest

- name: '4 Import VHD into VPC Image'
  inputs:
  - type: job
    stage: '3 Capture Initial VSI VHD to COS bucket'
    job: 3build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 4build
    type: builder
    build_type: customimage
    script: |+
      #!/bin/bash
      ./vpc-migrate-from-classic/pipeline_build.sh \
        040-import-image-to-vpc.sh 
    docker_image: l2fprod/bxshell:latest

- name: '5_Test_VPC_Image'
  inputs:
  - type: job
    stage: '4 Import VHD into VPC Image'
    job: 4build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 5build
    type: builder
    build_type: customimage
    script: |+
      #!/bin/bash
      ./vpc-migrate-from-classic/pipeline_build.sh \
        050-provision-vpc-vsi.sh
    docker_image: l2fprod/bxshell:latest

- name: '6_Clean_up_everything_except:_Image_COS_and bucket'
  inputs:
  - type: job
    stage: '5_Test_VPC_Image'
    job: 5build
    dir_name: null
  triggers:
  - type: stage
  jobs:
  - name: 6build
    type: builder
    build_type: customimage
    script: |+
      #!/bin/bash
      ./vpc-migrate-from-classic/pipeline_build.sh \
        060-cleanup.sh
    docker_image: l2fprod/bxshell:latest
#hooks:
#- enabled: true
#  label: null
#  ssl_enabled: true
#  url: https://devops-api.us-south.devops.cloud.ibm.com/v1/messaging/webhook/publish

