version: '2'
template:
  name: vpc-tutorials/vpc-migrate-from-classic Toolchain VPC Image Creation from Classic
  description: "Toolchain template description .\n\nTo get started, click **Create**."
  required:
    - repo
    - build

toolchain:
  name: 'vpc-image-{{timestamp}}'

services:
  # Github repos
  repo:
    service_id: githubpublic
    parameters:
      source_repo_url: "https://github.com/IBM-Cloud/vpc-tutorials"
      repo_name: "{{toolchain.name}}"
      type: clone
      has_issues: false
      enable_traceability: false

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: "Migrate from classic"
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          API_KEY: "{{form.pipeline.parameters.api-key}}"
          SOFTLAYER_USERNAME: "{{form.pipeline.parameters.softlayer-username}}"
          SOFTLAYER_API_KEY: "{{form.pipeline.parameters.softlayerapikey}}"
          DATACENTER: "{{form.pipeline.parameters.datacenter}}"
          REGION: "{{form.pipeline.parameters.target-region}}"
          #RESOURCE_GROUP_NAME: "{{form.pipeline.parameters.target-resource-group}}"
          RESOURCE_GROUP_NAME: "{{form.pipeline.parameters.target-resource-group}}"
        execute: true

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      datacenter: "dal13"
      #target-region: "us-south"
      target-region: "{{region}}"
      #target-resource-group: "default"
